### ISSUE TITLE
desktop app

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#1499]
[customer requested](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/552834264)

**Comment by crishoj** [comment]
+1 😬

**Comment by jeffandersen** [comment]
For now I've (literally) hacked together an electron app: https://github.com/jeffandersen/waffle-desktop

The codebase is frightening, due to needing to access particular references without any direct scope access, but so far the app has been really useful.

Hope that Waffle comes out with an official version someday.

**Comment by diasdavid** [comment]
Signing up for this one, would also like to have a desktop app that offers offline support.

**Comment by diasdavid** [comment]
btw @jeffandersen this is what I see after running your app:

![image](https://cloud.githubusercontent.com/assets/1211152/23955724/aa004f7c-0992-11e7-8f67-c551bf01499c.png)

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
