### ISSUE TITLE
Include source repos in badge numbers

### ISSUE THREAD

**Issue by lippytak** [waffleio/waffle.io#1555]
My team uses a meta-repo create a cross-project waffle: https://waffle.io/codeforamerica/health

As you can see there are 19 issues ready to go across projects:
![screen shot 2014-10-31 at 2 35 51 pm](https://cloud.githubusercontent.com/assets/2533112/4868944/e62f74de-6145-11e4-81f5-362a9d649cdf.png)

But the badge stats [on the meta-repo](https://github.com/codeforamerica/health) don't reflect the additional sources:
![screen shot 2014-10-31 at 2 36 07 pm](https://cloud.githubusercontent.com/assets/2533112/4868956/f6a3b4ce-6145-11e4-9c56-4bcb536052e6.png)

**Comment by brucellino** [comment]
I would like this too - I have several repos in a meta-project such as this one, and the waffle board is nice and full, however I can't summarise it with badges on external pages. Waffle should be able to read the source repos on the cards, extract the number of issues with various labels and add those to the full badge. I don't know how boards are rendered internally, but since it's able to show the correct number in the actual board, you should be able to generate the correct badge.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
