### ISSUE TITLE
Links in issue titles or content should open in a new window.

### ISSUE THREAD

**Issue by see8ch** [waffleio/waffle.io#1722]

**Comment by VinSpee** [comment]
I prefer the ability to open it in a new tab with Cmd+Click if I like.

**Comment by CodeMan99** [comment]
I would really like it if they provided a link it open the issue within their own modal. The number on the top left should still link to github.

**Comment by CodeMan99** [comment]
Related to #1466?

**Comment by armilam** [comment]
:+1:

Waffle.io is the kind of app that I'll have open for reference pretty much all the time. I see no need for links to open in the Waffle tab. Having links open in a new tab every time (instead of making me use Cmd+click) would be ideal.

**Comment by atz** [comment]
A daily dashboard interface should not assume you are done using it just because you want to follow one of the very many (external) links it displays.  Compare to gmail.

**Comment by VinSpee** [comment]
this is a drastically different app than gmail. I'd argue that a user is going to anticipate default link behavior.

**Comment by armilam** [comment]
It definitely is drastically different from Gmail, but it is the kind of app that is likely to be kept open for long periods of time, even while clicking links.

**Comment by atz** [comment]
A developer using this will be using it continuously every day, while performing work like accepting merge requests or pushing commits.  They are not opening it to **leave** the first time they need more info from a link.  Each detail view title bar links to the corresponding github issue, but those quite reasonably open in a new tab.  That already **is** the default behavior for the most common links in this application.

**Comment by VinSpee** [comment]
"Most common links in this application" vs "all of the Internet".

**Comment by CodeMan99** [comment]
@VinSpee Slightly separate concern, but I would like your opinion since you seem to be opposed to setting a new tab target by default.

What about if I say #1722 in comment like this one. Should it link to github like it is now, or should it bring up the model of that card in waffle? (There are already issues suggesting this... not in the mood to dig for a hour though.)

**Comment by VinSpee** [comment]
@CodeMan99 I would expect that it opens the card in waffle.

Here's my complete picture of this situation (as a daily user)

1. I expect that if I'm using waffle, I will stay using waffle. Taking me somewhere else without telling me (whether it's in a new window or not) feels odd. It may make sense to show some sort of indication that a link will take you out of waffle to Github (possibly an icon or something).

2. Avoid unintentional and unpredictable consequences. On the internet, the vast majority of the time, links open in the same window I'm currently using. If your target demo is people that use Github, there's probably a base level of technical competence you can expect from them. I'd think that includes _knowing how to open a link in a new tab if they desire_.

If you switch to opening any external link in a new tab, the problem is, as a user, __I can't undo this__. I can't say "hey i know this link is set to target="_blank", but ignore that and open it in this window". You'd not only be changing the default expected behavior of the internet, but also not giving users a choice.

**Comment by CodeMan99** [comment]
@VinSpee I think that's reasonable expectations.

> possibly an icon or something

In my opinion #1898 has some good examples of icon usage to help indicate a link will leave waffle.io.

**Comment by danquirk** [comment]
The problem is the behavior is inconsistent and waffle loads slowly enough and without remembering my place that it's very inconvenient to re-use the current tab.

When looking at a card for an issue:
- clicking the issue header takes me to the issue in a new tab
- clicking the author of the issue takes me to that page without a new tab
- clicking another issue referenced in the issue card takes me to that page without a new tab

This is more painful because waffle loads relatively slowly (not like hitting back in Gmail), and doesn't remember my place. So if I had filtered my columns to say a particular milestone, then clicked the wrong thing while inspecting an issue card, now I hit back, wait for waffle to load, then manually re-do my filters. It's quite annoying.

**Comment by dudewheresmycode** [comment]
+1 for this.

**Comment by dudewheresmycode** [comment]
External links should open in (`_target`) new windows/tabs. This seems to be the new norm for the whole internet. (Twitter, Facebook, Gmail). Especially if it's considered a "web-app", which waffle is, at least how I use it.

The idea being that clicking a link doesn't imply the desire to quit the app. So the app shouldn't quit and send the user along, it should remain open, while directing the user to the link in a new window.

**Comment by dudewheresmycode** [comment]
@waffle-team: Do you guys collect data on how many exits/referrals have the same URL? (i.e. How many users clicked back after clicking a link to an external website from waffle?) I'd imagine it's pretty high, and would support a need for this feature.

**Comment by benforged** [comment]
+1

**Comment by benforged** [comment]
this is especially frustrating with the new interface. very counterintuitive that clicking on the github icon at the bottom of a ticket obliterates my current tab

**Comment by benforged** [comment]
still a little counterintuitive that clicking on a user's name or a link dropped in an issue makes me lose this tab

**Comment by homeyer** [comment]
Shipped! :rocket:
