### ISSUE TITLE
view archived cards

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#1726]
Useful when going back to estimate old issues.

**Comment by homeyer** [comment]
[customer requested](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/andrew@waffle.io/conversations/694827213)

**Comment by andreackinney** [comment]
+1 I would like to be able to look back on previous quarters and see how many bugs were fixed,  how many features were added, etc.

**Comment by shacharz** [comment]
+1 especially useful when you're searching for an old ticket across multiple repositories

**Comment by sabbyanandan** [comment]
+1: This would be super useful.

**Comment by katschre** [comment]
+1

**Comment by shaharmor** [comment]
+1

**Comment by alexazarh** [comment]
+1

**Comment by lebolo** [comment]
+1

**Comment by abmaciel** [comment]
+1 This will be really useful because we need to  check about old issues

**Comment by alexazarh** [comment]
+1

**Comment by tornizanQ** [comment]
+1

**Comment by GilGald** [comment]
Guys this is really necessary +1

**Comment by IgorQuali** [comment]
+1

**Comment by pdobacz** [comment]
+1

**Comment by incompl** [comment]
+1

**Comment by anitakri** [comment]
+1

**Comment by Hcatel** [comment]
+1

**Comment by homeyer** [comment]
🎉   You can now see the last 30 days of closed and archived cards on the throughput page. You can get there by clicking the button in the done column after you archive your cards, or by navigating via the metrics icon in the sidebar.

We'll be improving this to let you select a bar on the throughput graph to see all the work that attributed towards that date range, so you'll be able to see all of your work back to when you closed your very first issue.

Feedback welcome!

**Comment by alexfornuto** [comment]
I don't think this really solves enough, at least not where I'm concerned. If I accidentally archive a card, and I'm not sure which it was, I can't find it from the throughput page. I'd prefer a place where I could see the latest archived cards.

**Comment by mosesoak** [comment]
I'm a Waffle user (love it) and am also confused by the Archive feature, since it has a nice clear way to archive cards but then no obvious way to access that list and un-archive items. I agree with @alexfornuto that the Throughput view is not really a solution. I understand that you probably don't want some new custom view, so perhaps just providing a control to make them show in the Done column would be a simple way to solve that. Opening an archived item could show the Archive button selected and provide the ability to deselect it to un-hide the card in Done in the standard view.

**Comment by Maxhodges** [comment]
how to view archived cards?
