### ISSUE TITLE
Option to assign user when using the Add Issue button

### ISSUE THREAD

**Issue by superkhau** [waffleio/waffle.io#1741]
When adding and issue via the `Add Issue` button in the top bar, there should be a dropdown allowing the user to assign the created issue to someone right away.

Right now, the process looks like this:

- Click `Add Issue`
- Enter issue title/description
- Click `Add` to create the issue
  - At this point the issue is unassigned
- Set the unassigned filter to find the issue
- Assign someone/yourself to the issue

All I want to do is `Add Issue` and assign a user when creating it so I don't have to do the filtering, etc.

**Comment by ashumz** [comment]
Hi @superkhau, 

Thanks for the request! We already have an open issue for this on our board here: 

https://waffle.io/waffleio/waffle.io/cards/5453c69c7abdfe69daba5b92

I added your +1 and tagged you in that issue so you can follow it if you'd like. We plan to add this in the future, just have not prioritized it yet due to other priorities. We are releasing the ability to add milestones at the time of adding issues within the next few days. Then we'll be working on adding labels at issue creation. Following that, we'll be adding assignment options as well. 

All the best, 

Ashley
