### ISSUE TITLE
No in ascending order

### ISSUE THREAD

**Issue by bvitinshtein** [waffleio/waffle.io#1751]
HI  ,
Then i am pressing plus and try select size there is no in ascending order (1,2,3,5,8)

**Comment by ashumz** [comment]
Hi bvitinshtein, 

Our sizes are based on the fibonacci sequence (commonly used for story size in agile methodologies like Scrum), rather than ascending numerical order. We have an open card for custom sizes schemas on our board here: https://waffle.io/waffleio/waffle.io/cards/54d20664703be30300e8c7ba

Feel free to add your thoughts or suggestion there! 

All the best, 

Ashley
