### ISSUE TITLE
Drag and drop to reorder often pushes cards to the bottom

### ISSUE THREAD

**Issue by tamarazuk** [waffleio/waffle.io#1770]
I'm having a hard time dragging cards to a different position. I was able to replicate the issue in Chrome and Safari, but it seems to be an intermittent issue in both browsers.

**Comment by ashumz** [comment]
Hi @tamarazuk, 

Sorry you ran into this! We have some known issues around intermittent drag and drop errors, especially in filtered views. There are some more details on our open issue (#1307) for this here: https://waffle.io/waffleio/waffle.io/cards/53ea6d9682b317f7d9ad84c9

That would be the issue to subscribe to in order to follow our updates to any of the card ranking issues you've experienced.  I'm closing this one out as a duplicate but will link to it from that card. 

Let us know if you have any questions! 

Ashley
