### ISSUE TITLE
permissions: switching from a private board to a public board prompts you to downgrade permissions

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#1777]
[customer reported](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/735989409)

**Comment by homeyer** [comment]
need to reach back out to understand the exact steps, unable to repro when just navigating from private to public.

**Comment by ashumz** [comment]
This situation also occurs when someone's access token expires/they log out, and then go to a multirepo board with a public primary source. 

We just ask for public permissions in this scenario based off the primary source. As a workaround, users shouldupgrade to private permissions from the project dropdown on the board in order to see private sources in addition to the public primary source.
