### ISSUE TITLE
Show repo name on mouseover

### ISSUE THREAD

**Issue by marcelog** [waffleio/waffle.io#1778]
When having multiple repos in the same board, the titlebar of each task is too short to show the repo name, it would be desirable to have a way of quickly looking at the full repo name, perhaps on mouse over showing some extra details with it

**Comment by marydavis** [comment]
Hi @marcelog,

What may help is creating a shorter display name for your repos instead of showing their full path name. To do this, click on the gear icon in your sidebar to go to the ‘Settings’ page. Then you can click on the pencil icon on the right side of any listed connected source to change its “Display name". Hopefully this helps :)

Thanks for the feedback!

Mary

**Comment by marcelog** [comment]
Ah my bad, that was exactly what I needed :flushed: 

Thank you!
