### ISSUE TITLE
Aging

### ISSUE THREAD

**Issue by luan-cestari** [waffleio/waffle.io#1821]
The issues/PR should have its age (how long since last update and when it was created) somewhere as this information is available in Github API v3 (Issues | GitHub API) and it is useful . With that information there are many possible feature that could be helpful, search as for issues that are waiting too much time for a comment or PR, a forgotten issue (as the time passed by it might became important), etc

**Comment by ashumz** [comment]
Hi @luan-cestari, 

We do show how long ago the issue was opened next to the issue creator's name in the card modal. We also show how long ago comments were made (ie: one minute ago, 3 months ago, etc.). I'm going to close this one out and move your comments to the Aging Trigger card, as that is more along the lines of what we might do with that available information. 

Thanks for all of the feedback and requests so far!
