### ISSUE TITLE
When a pull request has noone assigned, automatically assign the first (or last?) person who did a commit on the pull request branch

### ISSUE THREAD

**Issue by ebdrup** [waffleio/waffle.io#1835]
We are moving things fast in a Continuous delivery/deployment style. Most of the work is automatic for the developer and done from the command-line.
Automatically assigning goes hand in hand with your mission to never manually update a status again.

**Comment by ashumz** [comment]
Hi @ebdrup! 

Thanks for the request. :) If you use [GitHub's closing keyword](https://github.com/waffleio/waffle.io/wiki/FAQs#prs-closing-keywords) and reference an issue number in a pull request, we will automatically assign the PR to the person who issues the PR. 

If you don't want to use [GitHub's closing keywords](https://github.com/waffleio/waffle.io/wiki/FAQs#prs-closing-keywords), you can also use [Waffle's "Connect" keywords](https://github.com/waffleio/waffle.io/wiki/FAQs#prs-connect-keywords) prior to issue references, which will visually connect/nest the PR beneath the referenced issue and will also have the same assignment functionality. 

We originally did this behavior by default for any pull request that referenced any issue number, but we had many people get upset with the number of notifications they were receiving (since assignment triggers GitHub notifications). For that reason, we probably won't go back to any sort of default assignment unless users use the "Connect" or closing keywords mentioned above. 

Hope that helps! We are definitely interested in hearing more of your feedback around ways we can better optimize your workflow as you continue to use Waffle. 

Ashley

**Comment by ebdrup** [comment]
That doesnt really work as often the pull request is created without any preceeding issue. There is no issue to reference.

**Comment by ebdrup** [comment]
It's because of the way we work. Not everything is specified. We trust all our developers and if they spot a problem they fix it. Our continuous deployment works via pull requests. So we end up with a lot of unassigned closed pull requests. It would be super nice to be able to see in waffel who did those. 

Could waffel perhaps show the last comitter for pull requests witout an issue?
