### ISSUE TITLE
improve column setting interface

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#1852]
resolves #626, #1776, #569, #946, #780.

** Acceptance Criteria:**
- [ ] implement design from #1857
- [x] no duplicate columns!
- [x] change "In Progress Start" to "Work Started"
- [x] ability to create new label within label selector
- [ ] ~~show add column button when done/backlog columns are removed~~
- [ ] show overlay on done/backlog when trying to drag more than one column in the section letting user know only 1 column is allowed at a time.
- [x] confirm changes when attempt to leave page with unsaved changes

**Comment by burtonjc** [comment]
blocking until #1857 is done

**Comment by CodeMan99** [comment]
Love the new design! :heart: Excited to see it in action.

**Comment by thedrow** [comment]
I know I'm probably a bit late but this design doesn't take multiple workflows into consideration.
I created a workflow for bug reports and for features. Each workflow requires you to drag the issue through different columns.
Due to the fact that I can't create multiple backlogs with labels on them I created different columns. I think that allowing more than one backlog is a good idea but you should allow to optionally label them.

I'd love to have two different columns one beneath the other so that I can visually arrange my workflow for both bugs and features.
See https://waffle.io/celery/celery
