### ISSUE TITLE
Issue is not moved to In Progress automatically when using GitHub forks

### ISSUE THREAD

**Issue by artemrizhov** [waffleio/waffle.io#1861]
I've added my forked repo as a second source to the waffle board. Then I've unassigned myself from a task that was in progress, and moved that task to the Ready column. Then I've pushed branch `feature_#2_confirmation_page` to my repo. I was expecting the Issue will move to the In Progress column, but this did not happen. However I've got this message:

"We noticed you recently created a branch in GitHub with an issue number in the name. Did you notice that we moved the issue you referenced in your branch name to ‘in progress’ and assigned it to you?"

So, my answer is "no, I did not, but I'd really wish to".

**Comment by ashumz** [comment]
Hi @artemrizhov, 

We don't look at forks for moving things in progress currently. It sounds like that might be what you are running into. We have an open issue for this request here: https://waffle.io/waffleio/waffle.io/cards/544a857e7abdfe69dab9f1ba

Let me know if you think your problem is actually something besides this -- happy to look into it further for you. 

Ashley

**Comment by artemrizhov** [comment]
Hello Ashley! Please look further into this issue. It looks like my problem is not related to the issue that you pointed to.

I'm not asking to look at forks. Let's say "fork" == "repo2" in this case. So

1. I've added repo2 to the list of sources on the waffle project settings page.
2. Waffle has sent me a message saying "we noticed you recently created a branch with an issue number in it's name".

So, the system does look at repo2! It says "we noticed". So it DOES look in repo2. Otherwise I'd not receive such message, right? But it does not change the issue status for some reason.

**Comment by ashumz** [comment]
Hi @artemrizhov, 

I just tested this behavior on our end to ensure we weren't encountering any unknown bugs. I also looked into the event for triggering the issue (#2) to move to your In Progress column, and it appeared to work properly with this branch name for your repository. 

One thing to consider: which repository are you creating the branch on, and from which repository does the referenced issue live? If you are trying to move an issue from a repository outside of where the branch is being created, you'll need to use the following structure: username/repo#123. 

For example, if I want to move issue #2 on the waffleio/waffle.io repository, but I am creating the branch on the waffleio/waffle.io-app repository, I would need to name the branch as waffleio/waffle.io#2 in order for the correct issue to move In Progress. Otherwise, Waffle will think you're referencing the source repo for where the branch is created. Our full documentation on naming conventions for moving issues in progress is available here: https://github.com/waffleio/waffle.io/wiki/FAQs#branch-moving

Let me know if this fixes the issue!

Ashley

**Comment by jcrben** [comment]
Is it possible to add anything to the example branch name "waffleio/waffle.io#2" to give it something slightly more human-readable? We are currently using that for a group and it works but it would be nice to give the branch a hint of what the issue is about.

The documentation that FAQ page does not mention the waffleio/waffle.io#2 type of name.

**Comment by artemrizhov** [comment]
Hi @ashumz,

So, the problem probably is that the branch and the issue are in different repositories. I understand that this is needed because both repositories may contain same issue numbers. However, it does not make sense to specify the issue repository name in within the branch name in our workflow, because second repository is just a clone. We may use as many clones as we have developers in our team, but issues live in the central repo only. So we'd add same username/repo to each branch name. These are just needless word that I'm definitely not going to my branch names.

It would be nice if you add an option to track the issue numbers from all repositories. Maybe an option to specify which repo is central.

**Comment by ashumz** [comment]
Hi @jcrben and @artemrizhov, 

We use the GitHub naming convention currently which lets us have this functionality in a much simpler way. However, we could potentially use display names (editable in Settings->Sources) as aliases for the repo path. This would require a bit of work on our end and is not something we are immediately prioritizing, but we think it'd be awesome, so we opened #1891 to keep track of the issue. Please add your thoughts and +1's if you'd like to see it happen in the future. 

Cheers, 

Ashley

**Comment by artemrizhov** [comment]
@ashumz, while this will help to solve the problem that @jcrben noted in his comment, this is totally not useful in my case and does not solve the problem described in this ticket. I'd add +1 for the ability to set the issue repository in the settings, so that I don't have to add any unneded prefixes and suffixes to my branch names, because I already use prefixes for the task nature (i.e. feature, bug, etc), and adding one more prefix will make the branch names too complex.

**Comment by jcrben** [comment]
@ashumz - display names is cool, but I don't think this solves the problem that I was talking about. Nobody on my team was able to name branches anything but "waffleio/waffle.io#2" and retain the automatic moving. We were using a shared team repo and then working on branches in local forks, with the Waffle reflecting only our shared team repo issues. So your example in #1891 of "bug-fix-username/repo#123" or "bug-fix-myrepo#123" wouldn't work. We couldn't have anything but the repo names and the number of the issue. If I could prepend something like  "bug-fix" that would be great, but I wasn't able to get that to work. Maybe I'm missing something but if so the FAQ could be improved.

**Comment by artemrizhov** [comment]
@jcrben's could you please explain what you mean when saying "local forks? Are they github forks or just git-cloned local repositories? I'm a bit confused because "fork" is a github term, while "local" is usually something non-remote, i.e. on your personal work station.

**Comment by jcrben** [comment]
@artemrizhov good point - forget the "local" part; they are github forks.

**Comment by artemrizhov** [comment]
@ashumz, so as you can see, @ashumz's team uses same workflow as our team.

**Comment by artemrizhov** [comment]
@ashumz btw, you wrote

> We use the GitHub naming convention currently which lets us have this functionality in a much simpler way. However, we could potentially use display names

I think specifying default repo to search issue in is much more simple way than implementing display names. This should be just an option in settings, and just one simple check when your service choices right repository to deal with it's issues. Don't you think so?

**Comment by ashumz** [comment]
Hi @artemrizhov, 

Sorry I misunderstood your response. It sounds like for a multirepo board where you have several forks and one "main repository", that you'd like to be able to specify that all branches you create or pull requests you issue are referencing the main (specified in settings) repo's issues? Do you also have issues enabled in the fork repos, or only in the main repo? 

Thanks for the additional info. I'll run this by the team once you confirm and see what potential solutions may be available for future consideration. 

Thanks, 

Ashley

**Comment by ashumz** [comment]
@jcrben - I was able to replicate your issue when the extra information is added to the beginning of the branch name and will update the docs/check with the team if we need to have an issue created for the problem. You should be able to add additional info to the end of the username/reponame#issuenumber still. (ie: ashumz/so-simple-theme#10-bug-fix works but bug-fix-ashumz/so-simple-theme#10 does not work.) 

Thanks for noting this, and we'll let you know if we open an issue to be able to support the latter naming convention. Updating our docs now in the meantime. 

Ashley

**Comment by ashumz** [comment]
@jcrben@artemrizhov, 

I have created issue #1899 for this request. Our team discussed and we love the idea. May be a bit before we get to prioritizing it, though. Thank you for your patience, and let me know if there is anything else I can help with!

Ashley

**Comment by artemrizhov** [comment]
> It sounds like for a multirepo board where you have several forks and one "main repository", that you'd like to be able to specify that all branches you create or pull requests you issue are referencing the main (specified in settings) repo's issues?

Yes, exactly!

> I have created issue #1899 

Thank you!
