### ISSUE TITLE
Repo name truncated

### ISSUE THREAD

**Issue by mpgerlek** [waffleio/waffle.io#1968]
The GH repo name in the top bar of the issue display is truncated too much -- this could be better when using a long repo name and wide columns.

See attached screenshot.

**Comment by mpgerlek** [comment]
![image](https://cloud.githubusercontent.com/assets/742382/8287747/c51156d0-18df-11e5-8ba5-1536dbbb0031.png)

**Comment by mpgerlek** [comment]
![image](https://cloud.githubusercontent.com/assets/742382/8287766/f7c2b010-18df-11e5-98fc-85cbcbf9bcfd.png)

**Comment by mpgerlek** [comment]
![image](https://cloud.githubusercontent.com/assets/742382/8287790/20a2e216-18e0-11e5-98fb-28776edf4e4d.png)

**Comment by burtonjc** [comment]
Waffle does support assigning "display names" to your repos and that would help this. Just go into your project settings > sources (https://waffle.io/[owner]/[repo]/settings/sources) and click the pencil icon next to the repo name to add a display name for the repo. Then, instead of seeing the full repo name in the card header, you will just see the display name. Hope this helps!

**Comment by mpgerlek** [comment]
Ah, that's perfect solution - thank you!
