### ISSUE TITLE
ask to log in with private permissions when click on private project from home page (see also 1328)

### ISSUE THREAD

**Issue by marydavis** [waffleio/waffle.io#1973]

**Comment by ashumz** [comment]
A better solution might be 1328 -- expose when logged in with public repos and give clear CTA to upgrade to private/all repo scope. 

This will require we sort users' dashboards by public/private rather than just all projects for which they are a team member, but would ultimately be less confusing and a better experience. 

For users logged in with public scope, add a line on the main dashboard that says:
"Not seeing your project? You're currently logged in with Public permissions. Add private permissions to see private repositories, too." (or some variation of that language, to be defined)

**Comment by homeyer** [comment]
Yup I like that better

**Comment by ashumz** [comment]
closing this out in favor of #1328's solution
