### ISSUE TITLE
Handle renamed GitHub repos

### ISSUE THREAD

**Issue by imwithsam** [waffleio/waffle.io#2014]
I have a project "traffic-spy-skeleton" which I cannot delete. It was renamed to a different name, and we already have a new project for it. Now, waffle.io does not know how to delete the old project. I tried creating the repository on GitHub again, but it still won't delete.

**Comment by Swizz540** [comment]
Same thing for me.

When Github repositories are moved or deleted, Waffle keeps tracking on them.
But boards are accessible and not deletable.


The better solution must be to delete board when repository raise a `404`.

When repos are renamed, Github api raise a `304` with the new repository url as parameter.

If you use the `/repositories/:id` endpoint instead of the `/repos/:owner/:repo`
you will keep permanently eyes on tracked repo although they are moved.
(Renamed or Transferred to an another owner)

**Comment by homeyer** [comment]
Hey @imwithsam, we missed this notification the first time around. GitHub now supports redirects, so you can delete your old project (looks like you figured that out already though).

@Swizz540 - yep, until we fix that, I can delete any bad boards for you. Just reach out with the '?' icon in the app and tell us which repos you need removed.

**Comment by ashumz** [comment]
See also #2108

**Comment by homeyer** [comment]
Renamed this issue to account for all the situations that happen when repos are removed or renamed.
- [ ] a renamed repo should have all artifacts in waffle renamed as well - project name, source name, and card urls. Make sure it works for both the primary repo, and for secondary repos.
- [ ] a deleted repo should either auto remove from Waffle, or at least allow the board to be removed from Waffle.

**Comment by homeyer** [comment]
Tracking handling deleted repos on #2070, this issue will track renamed repos.

**Comment by ashumz** [comment]
#2258 tracks handling deleted repos, and #2070 tracks handling repos that a project member no longer has access to (ie: they were removed as a collaborator in GitHub)

**Comment by andschwa** [comment]
@homeyer Any update on this? What should we do to repos we just renamed?

**Comment by homeyer** [comment]
@andschwa you'll need to delete them and re-create them for now, sorry!
