### ISSUE TITLE
PR connects/fixes/resolves connections only work for "#123" and not github url

### ISSUE THREAD

**Issue by joesolly** [waffleio/waffle.io#2037]

**Comment by elia** [comment]
Noticed this too

**Comment by sam-github** [comment]
This makes it incredibly painful when PRs are connected to issues in other repos, and when it is done wrong, there is no way to see if you don't a) know about this pitfall, and b) press the edit description button so you can see the raw markdown (because github displays full URLs and short form identically when it renders).

**Comment by sam-github** [comment]
We love the connected to feature, but I can't count the number of times I have to fix this up manually, or explain to people why its so weird, and apologize about it.

**Comment by andreasohlund** [comment]
:+1:
