### ISSUE TITLE
rank not persisting correctly when moving cards in the same column and between columns when filtered

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2126]
[customer reported here](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/conversation/1271261621?nsrc=slack)

**Comment by ZCJ** [comment]
+1

**Comment by janaka** [comment]
Hi, any ideas on when this will get done?

**Comment by ashumz** [comment]
Hi all, 

We'll be getting to this shortly. In full transparency, our team is in the midst of shipping our first round of Waffle Takeout to GitHub Enterprise users. As soon as we've delivered on that, we've planned to address this issue right away. (Expected ETA of <7 days, but hopefully we'll be able to pull this work sooner.) 

In the meantime, I have asked for a bit more information from the team on how to replicate and/or avoid this issue. 

We believe the issue you're experiencing occurs when cards are newly added to a column (as new issues, from Waffle) and then ranked amongst other currently existing cards in the column. If this is the case for what you're running into, a refresh of the board *after adding new cards* should prevent the issue temporarily.

If that's not the case you're running into and that workaround does not fix the issue for you, please let us know so we can replicate on our end and be ready to swat all the bugs when our dev team pulls this work. :) 

Ashley

**Comment by ashumz** [comment]
I also confirmed this is happening when moving cards between columns on a filtered view. 

To replicate: search for a word that will result in multiple cards in multiple columns. For us, "experiment" 

Move a card from the bottom of Ideas that is returned in the search to the top of "Current Iteration". Refresh search. 

The card sometimes slips to the second or third ranking spot in Current Iteration rather than maintaining the filtered rank.

Expected behavior would be for the card in question to remain at the top of the column (or wherever it is placed) across refreshes.

**Comment by ashumz** [comment]
We have identified two additional issues which we will work to resolve with this current work in progress.

In a single browser:
1. Add 2 new issues to backlog
2. Comment on any card in any column
3. Rank for cards in that column changes (refresh of board fixes it)

With 2 browsers open:
1. Add 2+ new issues to backlog 
2. Move one of the new issues into the column to the right.
3. View rank in other browser - notice that it is different than what is displayed on the acting browser 

We are currently working on fixing these bugs - hang tight! You can avoid issues by refreshing after adding any new issues.
