### ISSUE TITLE
Better mobile support

### ISSUE THREAD

**Issue by waffleio** [waffleio/waffle.io#218]
@parasyte: "It looks and runs great on iPhone 4S, but scrolling each column is kind of "slow"; like it doesn't track my finger position well. Unless I scroll with two fingers, but that is awkward. Also missing the inertial scrolling to quickly flick through the list! I know iscroll exists as a workaround..."

Acceptance Criteria:
- Implement better column scrolling on mobile.
- Investigate dragging issues on mobile (create another issue for that if needed)

**Comment by ashumz** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/702602594)

**Comment by agibson22** [comment]
[+1](https://waffle.io/waffleio/waffle.io/cards/53440db224ceb40200d90fa5)

**Comment by gabeio** [comment]
:+1:

**Comment by M-Zuber** [comment]
Would really love this. I have a workflow setup that consist of github, waffle.io, and trello.
Being able to have w.io on mobile also would really help. Like @ashmuz said if not an app at last fluid site

**Comment by wjblair235** [comment]
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/918832260)

**Comment by chmac** [comment]
I'd suggest looking at Trello's mobile experience. Their apps are great. Not sure if you can get the same experience on mobile web, but I'd guess pretty close. I'd suggest that moving issues around requires a press and hold, then shake the card after the hold delay, and now let me drag it around. Then I can scroll more intuitively.

Also, the ability to add weight on mobile is really hard right now. It seems like I have to touch very precisely on the exact number to select it. It would be easier if I could hit anywhere on the row, rather than only on the text of the number (which is pretty small for the number 1 for example).

**Comment by doctorrustynelson** [comment]
+1

**Comment by tchalvak** [comment]
The current mobile (iOS 9, iPhone 5S) experience on waffle.io is essentially unusable.  Maybe even worse than that, since logging in for the first time may cause things to be moved around in a hard to see way that because of the windowing of the screen, can't be easily undone.

**Comment by ashumz** [comment]
[+1](https://github.com/waffleio/waffle.io/issues/2266)

**Comment by kellihsf** [comment]
+1 from [waffleio/waffle.io#2295](https://waffle.io/waffleio/waffle.io/cards/568fdf92123cfa9e00327dc5), closed as duplicate.  
"When on a small screen like a phone form factor:
1. Add Issue should become a view that takes over the whole view like a stack based UI
2. When viewing a card it should take over the whole view and be scrollable like a stack based UI
These two changes would be a huge improvement to the mobile web experience."

**Comment by freeranger** [comment]
+1

**Comment by gsouf** [comment]
Tested on android / chrome:

I'm on a board that groups many github repository, I want to create  an issue from this board , I can open the list of repository, but I cannot choose the repository in the list. Actually the list shows up, and immediatly disapears (not sure, but instead of disapearing it's like it becomes empty or content hidden)

**Comment by marydavis** [comment]
we just released some mobile improvements and will continue to make updates, please let us know any areas that are troublesome. thanks!

**Comment by mjumbewu** [comment]
@marydavis This is awesome! One thing I notice on a board with multiple repositories is that the long-touch-to-drag action works great on a narrow screen (e.g., my phone in portrait mode), but not as well on a wide touch screen (e.g., my phone in landscape, or a tablet). Most of the time my phone thinks I'm trying to select the repo name at the top of the card.

I'm wondering whether the draggable dots should just always be there, since they work with a mouse too?

**Comment by marydavis** [comment]
@mjumbewu thanks for the feedback! i'll create an issue to get that fixed :)

**Comment by marcos-scalabrin-tereos** [comment]
+1
