### ISSUE TITLE
Done / "Complete" Columns per Branch (ie: for issues merged onto staging and are ready for a QA phase, but not yet to master/default/production)

### ISSUE THREAD

**Issue by marksalpeter** [waffleio/waffle.io#2235]
## Use Case

We frequently will make a branch to add sets of new features. While working on the branch, typically a bunch issues will be created and closed. However, when we commit to the branch, the `closed #123` syntax, doesn't move the tickets to the completed section until after we merge the branch.
## Proposal

We would like to be able to add "completed columns" for a branch. When a commit closes an issue, it should be move to that branches completed column. When the branch is ultimately merged, the issues should be moved to the done column. 

Do you think this would possible? If not, how do you handle this workflow?

**Comment by ashumz** [comment]
Hi @marksalpeter, 

We have definitely thought about doing this (tying columns to branches for scenarios where a staging environment is the penultimate stage in your workflow.) We don't support it yet, though. 

One question for you -- would it be possible to branch off of a single "staging" branch for each new feature or set of features that you're adding? In this case, you'd issue pull requests for the addition of any new features to the staging branch, as in a Git Flow workflow. Maybe I am misunderstanding and you already do this, but I want to clarify since my best suggestion is dependent on your current workflow around pull requests - does your team use them today aside from when merging your staging branch into master? 

If you don't wish to share too many details about your internal workflow and prefer to have conversation outside of this issue/request, just shoot me an email at ashley at waffle.io, and we can chat more in depth. Happy to share how we do things over here, too. :) 

Ashley

**Comment by niemela** [comment]
+1 This would be very useful for us as well.

**Comment by prometheanfire** [comment]
I think this would also require a setting or a way to tell, per-issue, which is the final branch to wait for before the final close of the issue.  A way to list in the issue the branches you want to target would work too.  Right now we are using lists in issues to track that manually.

for instance...
- [ ] Master
- [ ] liberty-12.0
- [ ] kilo

**Comment by prometheanfire** [comment]
We are still updating this, but this is our workflow if you want to look.

https://github.com/rcbops/rpc-openstack/blob/master/CONTRIBUTING.md

**Comment by b3rnard0** [comment]
+1 Yes, we would this useful in our project.

**Comment by AnaMSteele** [comment]
Duplicate. Please upvote on #3278.
