### ISSUE TITLE
Ability to show metrics by month/day/year/etc...

### ISSUE THREAD

**Issue by johnmurphy01** [waffleio/waffle.io#2263]
On the metrics screen, it would be nice to be able to filter the metrics not only by week but also by day, hour, year, month or even a specific date range. We have daily deployments so it would be awesome to track our velocity by day.

**Comment by kellihsf** [comment]
Hi @johnmurphy01,

This issue is already being tracked at [waffleio/waffle.io#2297](https://waffle.io/waffleio/waffle.io/cards/568ff8b4ad0eb983005d524d) so we'll close this as a duplicate issue. I'll add your +1 and your comments to the existing issue.  You can subscribe to the issue in GitHub and add any additional comments or feedback around your use case to the existing card. Thanks!
