### ISSUE TITLE
Color PR to indicate their state

### ISSUE THREAD

**Issue by shacharz** [waffleio/waffle.io#2267]
Paint the PR icon to match its state:
blank - awaiting merge
red - closed (not merged)
purple - merged

**Comment by shaharmor** [comment]
+1

**Comment by kellihsf** [comment]
+1 from waffleio/waffle.io#2304, closed as a duplicate. 

"Colours - rather than green for open, grey for closed or merged, it would be better if these followed the colour scheme used in GitHub itself: Green=open, Purple=merged, Red=closed
Icon visibility - rather than a coloured icon on a white background, these would be far more visible if they were a white icon on a solid background, similar to those used in GitHub. This would also make it much easier to discern the colours e.g."

**Comment by shacharz** [comment]
I agree with @adamralph the color scheme should probably follow Github and not what I initially suggested.

**Comment by niemela** [comment]
+1

**Comment by adamralph** [comment]
:+1:

**Comment by adamralph** [comment]
@homeyer with reference to what I mentioned today 😉 

see also https://github.com/waffleio/waffle.io/issues/2353
