### ISSUE TITLE
Support for Task List

### ISSUE THREAD

**Issue by klarkc** [waffleio/waffle.io#2278]
Comments and texts with Task Lists from [GitHub Flavored Markdown](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) are not being shown like a checklist. Plus, in Github you are able to "Mark and Save" when you click in your own checklist item.

Example:

- [ ] Item 1
- [ ] Item 2
- [ ] Item 3

**Comment by homeyer** [comment]
Hey @klarkc - can you send a screenshot of what you're seeing? I'm seeing a checklist: 
![image](https://cloud.githubusercontent.com/assets/84629/12013377/58b9d6cc-ace3-11e5-9f69-1537ba514772.png)

And, I can click to mark them off. Maybe we're doing permissions wrong, since you're not a collaborator on this repo?

**Comment by klarkc** [comment]
@homeyer For some reason it is working now. If the problem reappears I will update here.

**Comment by homeyer** [comment]
closing for now, feel free to re-open if it happens again!
