### ISSUE TITLE
Github permissions are flapping

### ISSUE THREAD

**Issue by jasonkarns** [waffleio/waffle.io#2285]
I have two primary waffle boards that I interact with. One is a board that is a collection of public repos for which I am a maintainer. The other is for a private github repo.

Whenever I switch between them, GitHub repeatedly asks for permission modifications. The public repo waffle board only requires `public repo` access, while the private repo obviously requires `public+private repo` access.

Waffle should be smart enough that if my current github permissions are public+private, that I don't need to downgrade my authorization to public-only. Because every time it downgrades, I then have to re-authorize the upgrade to public+private when I log in to my private repo waffle board.

**Comment by jasonkarns** [comment]
![image](https://cloud.githubusercontent.com/assets/119972/12092750/fa46b980-b2cc-11e5-8ab2-b02cd949735e.png)

**Comment by jasonkarns** [comment]
Just a few hours later:

![image](https://cloud.githubusercontent.com/assets/119972/12096448/65afb558-b2e3-11e5-8b72-0ce2d57b43dd.png)

**Comment by kellihsf** [comment]
hi @jasonkarns,
Thanks for reporting this. This issue is already being tracked at [#2252](https://waffle.io/waffleio/waffle.io/cards/5660a1ab26f40228000e0e8f) so we'll close this as a duplicate. I'll add your comments to the existing issue card. You can subscribe to the issue in GitHub and add any additional comments/feedback to the existing card.
