### ISSUE TITLE
Improve Mobile Web Experience

### ISSUE THREAD

**Issue by mbrevoort** [waffleio/waffle.io#2295]
When on a small screen like a phone form factor:

- Add Issue should become a view that takes over the whole view like a stack based UI
- When viewing a card it should take over the whole view and be scrollable like a stack based UI

These two changes would be a huge improvement to the mobile web experience.

**Comment by kellihsf** [comment]
Hi @mbrevoort,

This issue is already being tracked at [waffleio/waffle.io#218](https://waffle.io/waffleio/waffle.io/cards/53440db224ceb40200d90fa5) so we'll close this as a duplicate issue. I'll add your +1 and your comments to the existing issue.  You can subscribe to the issue in GitHub and add any additional comments or feedback around your use case to the existing card. Thanks!
