### ISSUE TITLE
Better pull request icons

### ISSUE THREAD

**Issue by adamralph** [waffleio/waffle.io#2304]
* Colours - rather than green for open, grey for closed or merged, it would be better if these followed the colour scheme used in GitHub itself: Green=open, Purple=merged, Red=closed
* Icon visibility - rather than a coloured icon on a white background, these would be far more visible if they were a white icon on a solid background, similar to those used in GitHub. This would also make it much easier to discern the colours e.g.

![image](https://cloud.githubusercontent.com/assets/677704/12244756/73b80c46-b8a5-11e5-8215-e4c92ca0db07.png)
![image](https://cloud.githubusercontent.com/assets/677704/12244872/f4e390ec-b8a5-11e5-8d3d-8616a80b3705.png)
![image](https://cloud.githubusercontent.com/assets/677704/12244943/402d860c-b8a6-11e5-94f6-3b487a00afaf.png)

**Comment by kellihsf** [comment]
Hi @adamralph,

This issue is already being tracked at [waffleio/waffle.io#2267 ](https://waffle.io/waffleio/waffle.io/cards/566e975d238d9b950091b99a) so we'll close out this issue as a duplicate.  I'll add your comments and a +1 to the existing issue. You can subscribe to the issue in GitHub to track it's activity and you can add any additional comments or feedback around your use case to the  existing card. Thanks!

**Comment by adamralph** [comment]
@kellihsf https://waffle.io/waffleio/waffle.io/cards/566e975d238d9b950091b99a only duplicates the "colours" part of this issue but not the "icon visibility" part. In retrospect, I should have opened 2 separate issues. I'll open a separate issue for that now.

**Comment by adamralph** [comment]
I've opened the latter part as a separate issue - https://github.com/waffleio/waffle.io/issues/2353
