### ISSUE TITLE
Customised commands to move issues around

### ISSUE THREAD

**Issue by Imara** [waffleio/waffle.io#2307]
A possibility to create your own "commands" such as "Connected to". This way you could e.g. instantly move a merged & closed pull request to Staged by saying something like "Staging #224".

**Comment by ashumz** [comment]
Hi @Imara, 

Are you looking to have keywords based on connected or standalone pull requests being merged, rather than being merged and closed? (ie: when this PR gets merged, the PR and Issue should move to "Staging")? Or would you want to just include a column name from within a commit, followed by an issue number, to move the card there at the time you issue the PR? (This sounds like the "Work Started" action currently, which will dictate where "Connected" PR's go, as well as where issues move when you create branch names  with issue numbers.) The latter would be achievable by breaking down the actions in Settings->Columns to be more granular. 

Are one of those two options what you're requesting? Just want to make sure we're clear on what you're looking to do. :) 

Ashley

**Comment by niemela** [comment]
Can't this be done with labels?

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
