### ISSUE TITLE
Import/Export of waffle columns setup

### ISSUE THREAD

**Issue by WebDevJL** [waffleio/waffle.io#2328]
Hello,

I am using heavily your product. It is great and work wonderfully. 

However, for each new project I add, I need to replicate the columns arrangement I prefer using. 
You provide a default template but can you add a export / import feature so one can replicate the waffle columns setup from a project to another ?

Thanks in advance!

**Comment by kellihsf** [comment]
hi @WebDevJL,

Thanks for the request! This issue is already being tracked at [waffleio/waffle.io2157](https://waffle.io/waffleio/waffle.io/cards/562d118a698ba710004a32a9), so we'll close this as a duplicate. I'll add a +1 to the existing card for you. You can subscribe to the issue in GitHub to follow it's activity and leave any additional comments or feedback around your case use to the existing card.
