### ISSUE TITLE
Add ability to list issues that are "blocked" by other issues

### ISSUE THREAD

**Issue by DS-Matt** [waffleio/waffle.io#2334]
Currently our company uses Jira and the only really helpful feature in Jira that isn't in waffle is to associate which issues "block" other issues.  It would be a great feature to add.

Thanks!

Matthew

**Comment by niemela** [comment]
+1

**Comment by kellihsf** [comment]
Hi @DS-Matt, 

This issue is already being tracked at [waffleio/waffle.io#775](https://waffle.io/waffleio/waffle.io/cards/53445c8eebef97b1f9598d89) so we'll close out this issue as a duplicate.  I'll add your comments and a +1 to the existing issue. You can subscribe to the issue in GitHub to track it's activity and you can add any additional comments or feedback around your use case to the  existing card. Thanks!

**Comment by DS-Matt** [comment]
Hi @kellihsf -

Great, I'm going to do that, thanks!
