### ISSUE TITLE
Being able to expand board columns so that several issues fit in each row.

### ISSUE THREAD

**Issue by bgvo** [waffleio/waffle.io#2339]

**Comment by kellihsf** [comment]
Hi @bgvo,

This issue is already being tracked  [here](https://waffle.io/waffleio/waffle.io/cards/55f7c70e48a2381000a68ec6), so we'll be closing this one as a duplicate. I'll add your +1 to the existing  issue. You can subscribe to the issue in GitHub to follow its activity or add any additional comments or feedback around your issue to the existing card. Thanks!
