### ISSUE TITLE
gracefully handle what users see when GitHub is down

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#2369]
currently users see an internal server error when GitHub is down - we should show an error page
- [ ] should see a page letting them know we're having issues - make it fun - burnt waffle?
- [ ] have a link to to our status.waffle.io page 
- [ ] should show our contact email (support@waffle.io) w/ mailto link 

All of these things might help to limit the amount of tweet rage we get, too. :)

**Comment by marydavis** [comment]
could we not have an error page and let you continue to use Waffle and just show that we aren't updating with GitHub?

**Comment by homeyer** [comment]
I agree, our app should be able to handle it like any other error, and just show the normal red alerts when we can't do actions.
Maybe instead of the above, do this?
- [ ] make the app not show "Internal Server Error" when github is unavailable. The app should never give out 500s. It should load the UI, even if no data is available from the API.

**Comment by waffle-maker** [comment]
@homeyer can we estimate and schedule this?

**Comment by ashumz** [comment]
@homeyer can we estimate and schedule this?
