### ISSUE TITLE
shrinkwrap dependencies

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2378]
We get bit fairly often when npm dependencies aren't consistent between dev/prod/takeout.

**Acceptance Criteria**
- [x] use `npm shrinkwrap` on all nodejs services and components, fixing any errors that cause it to be inconsistent.
- [x] waffle.io-app
- [x] waffle.io-api
- [x] hedwig
- [x] waffle.io-hooks
- [x] waffle.io-models
- [x] waffle.io-helpers
- [x] waffle.io-env
- [x] add documentation for updating dependencies to waffle.io-app

**Comment by songawee** [comment]
Let's chat on the merge strategy with this one. It seems like we'll need to merge these changes into the respective repos and then go through a bump process for dependent repos. i.e. waffleio-app needs models, helpers, etc. We'll need to update the repos and then update the new shrinkwrap files.

**Comment by songawee** [comment]
Also, I don't think I needed it in this case, but there is a third party tool that helps with shrinkwrapping - https://github.com/uber/npm-shrinkwrap. I think it was created primarily deal with the shortcomings of npm 2 shrinkwrap. Since we have npm 3 and shrinkwrap was totally re-written, it seems to be less needed, but wanted to put it out there in case people think it would be helpful.

**Comment by songawee** [comment]
Also, we need to make sure when we bump packages, the npm-shrinkwrap.json gets its version updated as well. Grunt bump may do this, but https://docs.npmjs.com/cli/version also works.
