### ISSUE TITLE
Remember column collapse state across sessions

### ISSUE THREAD

**Issue by thomasknoll** [waffleio/waffle.io#2383]
Every time I reopen a waffle board that has been closed, all the columns are expanded, even though I have previously collapsed several columns.

Depending on the project (repo), I have a preferred view of the board based on collapsed/uncollapsed state. Currently I have to set that back up each time.

Preferably that could be saved at least at the browser level, if not settings/data level.

**Comment by marydavis** [comment]
@thomasknoll your selection of collapsed columns should be stored in your browser's local storage, do you happen to have that disabled or anything else that would block that from happening?

**Comment by Woodya** [comment]
i would request/recommend putting the column state in the url, so that it can be bookmarked and shared.
We have enough columns that it's nice to share an eng focused board with a group of participants and have them be able to quickly see the view we're talking about. To me, this has several obvious advantages over a single setting, or local storage, b/c i can have eng centric and biz centric states etc. simultaneously. Tho, from cold start i believe remembering a 'default' could also be nice, so i see why the local storage option has merit, net net i like the durability/sharability of url params.

**Comment by kellihsf** [comment]
@Woodya The initial request that was opened, is for a feature that is functional as described above. I think that's a different issue you're referring to so I opened a new issue here [#2600](https://github.com/waffleio/waffle.io/issues/2600) for it. We'll add it to our Ideas columns to gauge interest. Thanks!
