### ISSUE TITLE
Can't delete a source because is primary, but the source doesn't exists any more

### ISSUE THREAD

**Issue by ppazos** [waffleio/waffle.io#2414]
We needed to change the name of a repo, and want to update the waffle of that repo with the new name, we can add the new source but can't delete the old one because is "primary". Also there is no feature to change the primary source.

How do we do that? Thanks!

**Comment by kellihsf** [comment]
hi @ppazos,

You can delete a primary source by going to Project Settings->General.  If the primary source no longer exists, we can delete it from our end. You can email us at support@waffle.io with the details and we'll take it from there. Thanks!

**Comment by ppazos** [comment]
@kellihsf that deletes the whole project, not the primary source.

**Comment by kellihsf** [comment]
@ppazos,

Sorry, I misunderstood your question. You're not able to delete the primary repo only and keep the connected sources (we don't offer this capability at this time);  if you delete the primary repo it will delete the entire project as you mentioned. Because we don't support renaming repos yet,  your best best is to delete the whole project and recreate it.
