### ISSUE TITLE
Board is not being updated when computer comes out of sleep

### ISSUE THREAD

**Issue by adambuczynski** [waffleio/waffle.io#2425]
I work with Waffle on two computers. When I make changes on one of them, then later go to the other computer and open the Waffle tab, I am always forced to refresh the tab to see the latest changes. Can Waffle please update itself instead after the computer comes out of sleep? I have several other web apps that do this properly, so it should be possible. (Using a `lastChecked` or `lastAlive` timestamp comes to mind)

**Comment by kellihsf** [comment]
hi @adambuczynski,

This issue is already being tracked on [#1656](https://waffle.io/waffleio/waffle.io/cards/5485f3c77abdfe69dabb11da), so we'll close this as a duplicate. We'll be adding your comments to the existing issue. You can subscribe to the issue in GitHub or add any additional comments/feedback around your use case to the existing card. Thanks!
