### ISSUE TITLE
"Automate" the process of joining team projects

### ISSUE THREAD

**Issue by brentrobbins** [waffleio/waffle.io#2436]
The idea is to make it more automated/automatic where if you are already on the team of a gihub repo and someone creates a Waffle project the members are automatically joined to the project. 

This will be nice so you don't have to make sure everyone on your team clicks the link you send out or also manually adds the repo/project.

**Comment by homeyer** [comment]
What if Waffle just shows you any project that exists for a repo that you have access to?

So, someone still has to create the project, but then everyone would see it.

**Comment by brentrobbins** [comment]
I thought it already kind of does that. So you can click the + icon see
what's available and add it, but I am looking for it to automatically add
it to all of the github team member's waffle projects without having to do
anything extra. Does that make sense?

On Thu, Mar 10, 2016 at 1:31 PM, Andrew Homeyer <notifications@github.com>
wrote:

> What if Waffle just shows you any project that exists for a repo that you
> have access to?
>
> So, someone still has to create the project, but then everyone would see
> it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/waffleio/waffle.io/issues/2436#issuecomment-195034597>
> .
>



-- 
Variant Studios, Inc.
120 W. Olive Suite #208
Fort Collins, CO 80524
970.405.2777
https://www.variantstudios.com
Twitter <http://twitter.com/variantstudios> Facebook
<https://www.facebook.com/variantstudios> Instagram
<http://instagram.com/variantstudios>

**Comment by burtonjc** [comment]
Is your hope to just make team on-boarding easier? Or are you trying to insure Waffle's auto-work tracking feature can act on behalf of all users on the team?

**Comment by homeyer** [comment]
Implementation idea:
- when a new project is created, or a source is added, look at all the collaborators (and viewers for private?), union against waffle users (just with a find `github.login` `$in`), and auto add them to the team
- when a new user is created, do the opposite. Find repos they have access to, and find matching projects.

The second is a bit process heavy, I personally have access to hundreds of repos and that takes a bit to ask GitHub for. Instead of automating all of this during user or project creation, we could prompt users to join projects they have access to when they first join, or whenever they create a new project. 

Not sure what the better experience would be. For the first, we'd have to improve the UX to explain these are existing Waffle projects that they're automatically a part of, and organize them better by org. There are so many repos in GitHub I don't care about that I have access to (private repos), I want to make sure my Waffle dashboard doesn't become a quagmire of projects I don't want to watch.

**Comment by brentrobbins** [comment]
I think the first method would be a great way to stat improving the initial
on-boarding for team members to the newly created waffle projects. I am
also thinking this would only be 'activated' on creation with the current
git members and something that needs to be continually updated with newly
added git repo team members after the fact.

On Thu, Mar 10, 2016 at 7:26 PM, Andrew Homeyer <notifications@github.com>
wrote:

> Implementation idea:
>
>    - when a new project is created, or a source is added, look at all the
>    collaborators (and viewers for private?), union against waffle users (just
>    with a find github.login $in), and auto add them to the team
>    - when a new user is created, do the opposite. Find repos they have
>    access to, and find matching projects.
>
> The second is a bit process heavy, I personally have access to hundreds of
> repos and that takes a bit to ask GitHub for. Instead of automating all of
> this during user or project creation, we could prompt users to join
> projects they have access to when they first join, or whenever they create
> a new project.
>
> Not sure what the better experience would be. For the first, we'd have to
> improve the UX to explain these are existing Waffle projects that they're
> automatically a part of, and organize them better by org. There are so many
> repos in GitHub I don't care about that I have access to (private repos), I
> want to make sure my Waffle dashboard doesn't become a quagmire of projects
> I don't want to watch.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/waffleio/waffle.io/issues/2436#issuecomment-195149154>
> .
>



-- 
Variant Studios, Inc.
120 W. Olive Suite #208
Fort Collins, CO 80524
970.405.2777
https://www.variantstudios.com
Twitter <http://twitter.com/variantstudios> Facebook
<https://www.facebook.com/variantstudios> Instagram
<http://instagram.com/variantstudios>

**Comment by burtonjc** [comment]
This is done. Now, new Waffle users will be added to all the projects they have access to, and new Waffle projects will automatically show up for all Waffle users who have access to them.
