### ISSUE TITLE
grant/request access permission for new organization

### ISSUE THREAD

**Issue by retog** [waffleio/waffle.io#2446]
When I first register I could grant or request access to github organizations I was a member at the time. Now I'm in a new organization and can't find a way to access it from waffle.

**Comment by kellihsf** [comment]
hi @retog,

You'll need to revoke Waffle for your personal GitHub username in order to authorize at the organization level, as an admin of the organization. (If you're not an admin, you'll need to ask a user who is an admin take these steps)

To do this, go to Settings->OAuth Applications in GitHub. Revoke access to Waffle.io. Now you can log out of Waffle and back in, and will be prompted to select which organizations to allow access for. If your organization has third party application restrictions enabled, you should see an option to "Grant Access" for that organization.

**Comment by kellihsf** [comment]
hi @retog,

We'll be closing this issue for now. Let us  know if you have any questions, thanks!
