### ISSUE TITLE
Allow new issues from external contributors to go into a different column

### ISSUE THREAD

**Issue by dianashk** [waffleio/waffle.io#2495]
There is already a mechanism in place that works exactly as expected for Pull Requests opened by external contributors. We'd love to see the same level of customization for issues. It's important to our open source project to know which issues require special care and attention because they are from folks not on the core team.
Thanks in advance! We are huge fans of your work and really appreciate everything you guys are doing. Cheers! :heart: :wave:

**Comment by homeyer** [comment]
It's a bit of a manual process, but we handle that case by making our first column the "Inbox" where new issues go, and then have another column for "Planned" for things that have been vetted. If a teammate opens it they can move it to the appropriate column themselves, otherwise we go through and triage the Inbox on a regular basis.

Would that process work for you? Totally get the thought behind auto moving the issues as well.

**Comment by dianashk** [comment]
That's the process we use ourselves, but it would be nice to have it supported automatically.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
