### ISSUE TITLE
Updating the description of an issue on Github and moving the issue on Waffle resets the description

### ISSUE THREAD

**Issue by alexquintino** [waffleio/waffle.io#2511]
Steps to reproduce:

1. Open a tab with Waffle
2. Open a tab with a Github issue
3. Update the issue description on Github
4. Move the issue between columns on Waffle
5. Refresh the Github tab. The changes are lost and the description is back to the previous state

Refreshing Waffle or opening the issue on Waffle before moving it fixes the issue.

Possibly related to #2505 or #2478

**Comment by kellihsf** [comment]
Hi @alexquintino,

Yep, this is a known issue. If you update an issue title in GitHub, (and nothing else) we don't get webhooks from GitHub for this action so we have no way of knowing about this change. So if you only change the title in GitHub and then move the card in Waffle, and there were no actions that trigger webhooks (add a comment, change label), we'll change it back to the original title.

If you change the title in GitHub and make other changes (comment, label), this will trigger the webhook and then everything will be updated on the Waffle board in real time.

You are correct, this issue is related to [#2505](https://waffle.io/waffleio/waffle.io/cards/5719056bfbe106d4007afc88) and should be  resolved when #2505 is implemented. :)
