### ISSUE TITLE
Allow independent custom board name

### ISSUE THREAD

**Issue by henrydobson** [waffleio/waffle.io#2604]
Allow custom board name independent of primary repo name. Custom board names are currently possible but it also changes the name on all of the primary repo cards for that board.

**Comment by connormlewis** [comment]
I would also really like this feature. It makes sense when you're working with a waffle board that connects to several repositories.  In this case, you may have `project-iOS`, `project-Android`, and `project-api`.  None of these make sense to be the name of your waffle board and it would be better to simply have `project` as the board name. But as @henrydobson said, you wouldn't want this to change the name on all the api cards, because that doesn't make sense either.

**Comment by adamwitko** [comment]
+1 for this.

Recently signed up to Waffle.io and we are going to have one board that has up to 50 repositories linked to it. We really want this to be named independently of the main source repo.

**Comment by Codesleuth** [comment]
We're using the board to track features across repos which represent components of a project, and being able to set the name independently would reduce the the confusion we're seeing here.

**Comment by WanderingMatt** [comment]
+1

We'd like to be able to have a master project that contains all of our repos as well as more focused projects that contain individual products.

**Comment by jdmaresco** [comment]
+1 – I second the use case with multiple mobile platforms. Doesn't make sense to call the board iOS or Android

**Comment by rmateu** [comment]
+1 on this (Browser extension repos is my use case). 

Thanks to the head up to this request from @waffleio on twitter.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
