### ISSUE TITLE
set "owner" field on account

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2636]
**Acceptance Criteria**
- [ ] add an "owner" field to account model
- [ ] set "owner" correctly when creating new accounts
- [ ] fix code to use `owner` instead of `name`
- [ ] migration that sets the owner field to the github login of the user, based on the name of the account. "burtonjc's account" will set the owner to "burtonjc".
- [ ] migration also removes name
- [ ] remove "name" from account model
- [ ] index owner

**Comment by burtonjc** [comment]
I think this has to happen in 3 steps:

1. Adding `owner` field
  - [ ] add `owner` field to account model
  - [ ] set `owner` field when creating new accounts
  - [ ] migration to add `owner` field to existing accounts
    - [ ] index `owner` field
2. Use `owner` instead of `name`
  - [ ] fix code to use `owner` instead of `name`
    - [ ] App client
    - [ ] App server
    - [ ] API
3. Get rid of `name` field
  - [ ] migration to remove `name` field
  - [ ] remove `name` from account model
