### ISSUE TITLE
Combined projects board

### ISSUE THREAD

**Issue by abeMedia** [waffleio/waffle.io#2730]
It would be great to have a board displaying either all or a selected number of projects (rather than just one). This would be especially useful for people maintaining multiple smaller open-source projects (such as myself).

**Comment by kellihsf** [comment]
Hi @abeMedia,

Do you know about our multiple repo boards? You can connect as many repos as you'd like to a single board in Waffle to create a multi-repo board, which will give you an overview of all of your issues across multiple repos. You'll just go to Settings->Sources and click on the green GitHub icon to select the repos you want to add.
More info on this here: https://github.com/waffleio/waffle.io/wiki/FAQs#multi-repo

**Comment by abeMedia** [comment]
That's really great but sadly it removes the ability to see just that project on it's own. I will probably resort to creating empty repos to use as "master" project and still keep each one on it's own as well but ideally I'd like to see an option for creating a project that isn't tied to a repo (if your current architecture allows this).

**Comment by kellihsf** [comment]
hi @abeMedia,

You can view the main repo by itself if you filter by source and choose that main repo. You can then bookmark that filtered view, because the filter saves in the URL.

Currently, you're not able to create a project without it being tied to a repo. We're tracking the request for this on [#2074](https://waffle.io/waffleio/waffle.io/cards/55e734b972422f0f003bfd50). We do have a few non-code repos in GitHub that we create boards for (business, support issues) which works for us. :)

**Comment by abeMedia** [comment]
Thanks, I'm taking the non-code repo approach.
