### ISSUE TITLE
Add CFD (Cumulative Flow Diagram) to metrics

### ISSUE THREAD

**Issue by linusl** [waffleio/waffle.io#2786]
Generate CFD per board including WIP/throughput, WIP/Lead time etc. Reference here: http://open.bekk.no/cumulative-flow-diagrams-with-google-spreadsheets

**Comment by sarbogast** [comment]
With Trello, we used this simple tool http://www.nicoespeon.com/trello-kanban-analysis-tool/, and it displayed exactly the metrics we needed to do our retrospectives: based on a start and end date, in and out columns, throughput, total WIP and lead time. Would be nice to also have cards stuck in an in-progress column for more than x days, in order to identify bottlenecks more quickly.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
