### ISSUE TITLE
ability to rename a board

### ISSUE THREAD

**Issue by 1000lbsofbison** [waffleio/waffle.io#2818]
Boards can only be set to a repo name.  Withy many repos worth of issues being aggregated into one board for my team to work off of, its a bit of a misnomer to have our board called repo1 when it consists of issues from repo1, repo2,...

**Comment by kellihsf** [comment]
Hi @1000lbsofbison,

You're able to set a new display name for your Waffle project by going to Settings->Sources and rename the first source listed (this is your primary source if you have multiple sources listed.) If you set a display name for your primary source, we will use this as the project name in the project dropdown, cards, and dashboard for all team members on the project. If you do change the display name for the project, the primary repo name would change too. Thanks!

**Comment by kellihsf** [comment]
We'll close this issue for now; let me know if this isn't what you're looking for!

**Comment by kathykeating** [comment]
this solution isn't desirable.  Imagine the case where we have two repos for a single application:
- project_back
- project_front

These two repos, together, implement a full stack application, but we want to manage the issues/PRs from both on a single board.  Our board name needs to be "project" which encompasses the meaning of the entire application. 

Instead, today, we are stuck with the board name being either "project_back" or "project_front" which is not clear and is not accurate.  

Ideally we want to be able to set the board name independently of the two source names.  So that everything remains clear.

**Comment by katewardin** [comment]
We have the same use case as @kathykeating  and want the ability to change the name of the product board without changing the names of the repos on the individual issues.
