### ISSUE TITLE
sometimes WaffleBot doesn't pick up changes on PRs and issues

### ISSUE THREAD

**Issue by kellihsf** [waffleio/waffle.io#2840]
Investigate errors with WaffleBot; sometimes actions are being shown taken by a user not by WaffleBot

**Comment by kellihsf** [comment]
![screen shot 2016-11-11 at 4 46 34 pm](https://cloud.githubusercontent.com/assets/4775572/20233660/2aad4f14-a82f-11e6-9808-0821b5cbc2a4.png)

![screen shot 2016-11-11 at 4 51 38 pm](https://cloud.githubusercontent.com/assets/4775572/20233662/2fa24ed4-a82f-11e6-8a5c-ae13126482cc.png)

**Comment by kellihsf** [comment]
<img width="703" alt="screen shot 2016-12-29 at 3 54 02 pm" src="https://cloud.githubusercontent.com/assets/4775572/21556608/14b718d6-cddf-11e6-9248-04be0d2e644d.png">

^issue is in 'In Progress'

**Comment by burtonjc** [comment]
We see a lot of mongo Version Error mismatches in wafflebot. the current theory is: installations have an array of tokens that get modified frequently, multiple modifications at once cause the version errors. When those version errors happen, wafflebot drops the event.

**Comment by homeyer** [comment]
is there better logging we need to verify this first? e.g., log the intended action and then whether it was successful or not? Or, do we already have that?

**Comment by flatcap** [comment]
Me too.

My repo [neomutt](https://github.com/neomutt/neomutt) has quite a lot of labels being added/removed by user "ThomasAdam" (the first user I added to the organisation).  I can't see a pattern, though.

Also, when a issue is moved to the "done" column, the bot sometimes assigns a user to it.

It would be helpful if you published the set of rules that the wafflebot follows.
Then we'd know what was expected and what should be reported.

Cheers, Rich.

**Comment by burtonjc** [comment]
WaffleBot is built using the new [Integrations API](https://developer.github.com/early-access/integrations/). Part of what that involves is tracking `installations` and access tokens for each `installation`.

There are two things we should look at as a start to fixing WaffleBot.
1. It would appear that something changed since we originally wrote WaffleBot and now we are getting a lot of [errors in installation-middleware.ts](https://rpm.newrelic.com/accounts/634412/applications/24567719/traced_errors/3ba72f8e-f9ed-11e6-8137-f8bc12425498_0_2221/similar_errors?original_error_id=5140f2c1-f9f0-11e6-8137-f8bc12425498_0_2221). This _could_ be a pretty easy fix to ease a lot of the pain.
1. A bigger issue is getting rid of the [mongoose `VersionError `s](https://rpm.newrelic.com/accounts/634412/applications/24567719/traced_errors/a6ef9f98-f9ed-11e6-8137-f8bc12425498_0_1994/similar_errors?original_error_id=a6ef9f98-f9ed-11e6-8137-f8bc12425498_0_1994). Those occur when multiple updates to an embedded array occur at the same time. Currently, access tokens for an installation are tracked on an embedded array on the installation object itself thus exposing us to the `VersionError `s. This is the most likely culprit for the errors. To fix it we will need to:

    1. Add a new DB collection for installation access tokens that look just like the embedded documents on installations now, but that also track which installation they belong to using a ref id to the installation.
    1. Update WaffleBot to us the new collection instead of the embedded collection of tokens.
    1. Verify that the `VersionError`s have ceased.
    1. Script to blow away all the embedded token arrays.

**Comment by homeyer** [comment]
Since we're blocked from using ngrok right now, lets do this as a first step:
- [ ] write an integration test that can consistently reproduce the `VersionError`

**Comment by burtonjc** [comment]
I think we could get a test that frequently causes the `VersionError`, but it will still be a race condition that might pass sometimes.
