### ISSUE TITLE
Renamed repo on GitHub not synced with project list

### ISSUE THREAD

**Issue by aknuds1** [waffleio/waffle.io#2880]
When renaming a repo on GitHub that is part of your projects on waffle.io, it doesn't seem as if the project list is updated with the change.

What I did was to add the renamed repo to waffle.io, but the old name for the repo is still in my waffle.io project list. I can't remove it either AFAICT.

**Comment by kellihsf** [comment]
Hi aknuds1,

Sorry for the late reply here! Are you still having trouble with this? One thing to note is that after you've renamed a repo in GitHub, you'll just visit the previous URL and you won't need to create a new board for the newly renamed repo because it will automatically be redirected. (Creating a new board will causes issues). Have a look at our [FAQ page](https://intercom.help/waffleio/faq/board-configuration-and-settings/i-renamed-or-transferred-my-repo-in-github-what-happens-to-my-waffle-projects-for-that-repo) and let me know if you have any questions!

**Comment by aknuds1** [comment]
@kellihsf At least a project rename on GitHub isn't applied immediately in waffle.io, I just tested. Not sure if it takes time to sync or what. However, after a few clicks on the project in waffle.io's project list, the project name eventually got updated in waffle.io and I could click into it (at first clicking on it did nothing).
