### ISSUE TITLE
look into burndown end date for size vs count last closed

### ISSUE THREAD

**Issue by marydavis** [waffleio/waffle.io#2889]
also check why size 0 line is still there

**Comment by Delta-TO-EngrPMO-Jay** [comment]
@marydavis I don't want to add a duplicate feature request, and this issue sounds similar or at least related. our team would like to see an ecd, but as real estate is at a premium and burndowns are the measure, we envision a numeric countdown of days remaining calculated off an ecd entry in the right-hand with the assignees, size, labels, and milestones. Is that also your vision? Thanks

**Comment by homeyer** [comment]
I think the original issue is a date bug that happens intermittently. 

@Delta-TO-EngrPMO-Jay - so you're suggesting having a "predicted finish line" that is drawn based on past dots? Sorta like the red line in this mockup?

![image](https://cloud.githubusercontent.com/assets/84629/21147430/3c21ab9a-c112-11e6-8ff9-747ca6aaa1f2.png)

**Comment by Delta-TO-EngrPMO-Jay** [comment]
@homeyer I think so. an ecd (calendar) in the right-hand of the "comment" dialogue that the assignee could update as needed/things change to represent when he/she expects or promised to deliver it. represented by a numeric countdown on the card similar to the "size" #, perhaps surrounded by an octagon instead of a circle...thinking stop sign. this would clearly communicate to the team when it is due/expected to produce, could be used to sort/prioritize the cards in the columns to convey the order they are expected to produce, would also communicate to other resources where/when it may be necessary to subordinate to the constraint/dog-pile in order to meet the promised date, could also change colors based on whether an "expedite" or "help needed" tag is added and promised date <? days. We are emailing a screenshot weekly of our Waffle board to all our CA PPM user as a status report...so, it would be of value to them as well. sorry @marydavis if I hijacked this issue/idea
![delta-to-engrpmo waffle board](https://cloud.githubusercontent.com/assets/24273904/21149041/1b6df906-c128-11e6-99cc-6fa653e4003a.jpg)

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
