### ISSUE TITLE
Clear assignees and labels for new issues

### ISSUE THREAD

**Issue by sernaashui** [waffleio/waffle.io#2905]
When the Add Issue button is clicked, the issue window opens with the last assignees and labels already selected.

**Comment by kellihsf** [comment]
hi @sernaashui,

This is actually the intended behavior when creating an issue to save you time since your previous selections are already pre-loaded. All fields will be saved except for labels (repo, assignee, milestone) until they're changed. Are you seeing that previous labels are being saved too? Thanks!
