### ISSUE TITLE
investigate using Radar instead of `address_zip_check`

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2916]
Some customers can't buy metrics because zip check verification fails.

It would be awesome to rely on Stripe's Radar feature to do zip check verification instead, but we need to make sure everything works fine with Avatax if we remove the  `address_zip_check` code and instead turn on Radar zip check.

AC:
- [ ] we're notified when a zip fails, at a minimum, so we can reach out to the user. could be in stripe with radar or in newrelic, as long as we know when it happens and doesn't go by unnoticed.

Possible solution:
- remove `address_zip_check` in code
- turn on Radar zip checking
- verify Avatax looks ok when an invalid zip code is used

**Comment by songawee** [comment]
Seems like we should  handle 'unavailable' zip codes - https://support.stripe.com/questions/what-is-avs#what-if-the-address-checks-show-as-unavailable

**Comment by songawee** [comment]
After reading through the docs on Radar on stripe's website, here is what we get for the zip checks (Radar does MUCH MUCH more regarding fraudulent charges):

we can "Allow", "Block",  or "Review" transactions based on whether or not the zip code checks fail. Per the docs on Radar zip checks:

```
Payments that fail a bank or card issuer’s ZIP code verification check are blocked. If the ZIP code is not provided, or the customer’s bank doesn’t support its verification, the rule cannot block the payment.
```

So, we could "review" or "allow" those zip checks where the bank does not support verification. The review process is manual and part of a queue within the stripe dashboard.

If we let those charges go through, Avalara would have to handle those zip codes. Here is what I've found regarding how Avalara:

In Avalara's test mode at least (didn't want to hit prod just yet), it appears as though Avalara will respond with a 400 if the address is all out bad, i.e.

` Piazza San Marco Venice, US, 30100` (should be country IT instead of US)

Avalara will respond with 0 tax for addresses that appear to be unavailable in stripe, i.e. (customer reported)

`123 Garbage St., Amsterdam, NL, 1066 EP`

They also indicate that the taxAuthorityType is `-1` (usually > 1 for valid tax authority types)

My proposal is that we adjust our stripe zip check to only fail on `fail` and pass everything else through to Avalara since 0 tax is the result in that case.

Error reporting:

We can wire `fail` cases from stripe with new relic on the client. Any request that fails to Avalara will result in a (un-helpful, but visible) error to new relic and reported to the stripe logs which eventually bubble up to an email I believe.

**Comment by burtonjc** [comment]
I'm a :+1: on your proposal. Will we need to pay for NewRelic Browser to track the client side errors?

**Comment by songawee** [comment]
ah, yeah. I saw that we're already loading new relic on the client and thought it would work. In thinking on this more, it seems like we wouldn't want to report the fails in case someone accidentally put in a bad zip, realized it, and fixed it. might not make sense in that case to reach out.

**Comment by burtonjc** [comment]
Cool. I say let's go for it! Update the `if` check to only block `failed` checks and let hooks handle the error reporting.
