### ISSUE TITLE
right click on projects should open them in a new tab

### ISSUE THREAD

**Issue by kellihsf** [waffleio/waffle.io#2965]

**Comment by burtonjc** [comment]
This is talking about the user dashboard page. The problem is that the projects are not actual links (anchors). Thus, the browser doesn't know to treat them as such. If we fix it correctly, we should get both of these behaviors:
- [ ] cmd+click on project opens it in a new tab
- [ ] when right clicking on a project, there is an option to "Open in a new tab"
