### ISSUE TITLE
Can't expand column after column collapse

### ISSUE THREAD

**Issue by rete** [waffleio/waffle.io#2967]
After a column collapse, the column title is reverted and the expand button doesn't appear anymore. The column is in the same state after a refresh. 

I'm using firefox (iceweasel) 38.5.0

**Comment by kellihsf** [comment]
Hi @rete,

This issue is most likely due to an older version of Firefox that you're running Waffle on.
Older versions of Firefox do not support the collapsible columns. This feature was created using CSS that works with version 41 and up, so we recommending updating Firefox to the latest version. Thanks!

**Comment by rete** [comment]
You're right! Fixed after a Firefox update. 
Thank you!

**Comment by kellihsf** [comment]
Great, you're welcome! :)
