### ISSUE TITLE
Client Secret leaked in HTML sources

### ISSUE THREAD

**Issue by kotireddyaluri** [waffleio/waffle.io#3066]
I have observed client secret in html source when I logged into the application.

Which should not be happen.

Thanks,
Koti

**Comment by homeyer** [comment]
Hey Koti,

We inject the secret in the html so the application can make API requests from the client side. The token is tied to your user, it's perfectly acceptable for you to grab your own token and make requests to the API using it. No one else can grab it since the page is served over HTTPS.

The API is session-less and stateless. There's no other way to validate a user's authorization, like relying on a session tied to a cookie.

**Comment by homeyer** [comment]
A client secret, or an access token?

We inject the access token for the Waffle API in the html so the application can make API requests from the client side. The token is tied to your user, it's perfectly acceptable for you to grab your own token and make requests to the API using it. No one else can grab it since the page is served over HTTPS.

The API is session-less and stateless. There's no other way to validate a user's authorization, like relying on a session tied to a cookie. 

I wasn't able to reproduce finding a oauth client secret in the html, can you provide more details?

**Comment by kotireddyaluri** [comment]
No no, This issue you have already Fixed, just for the record purpose I have filed here.
I am closing this issue.

Thanks,
Koti

**Comment by homeyer** [comment]
Oh, sorry!!! Just saw your email :)
