### ISSUE TITLE
rework column height calculation to use css and not js math for performance

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#3101]
check for cross browser horizontal scrollbars, zooming, banners, and mobile

**Comment by homeyer** [comment]
example of `vh`: https://github.com/waffleio/waffle.io-app/blob/master/client/styles/app/board/column.less#L10

**Comment by heybenji** [comment]
While you're at it, fix overall page sizing on iPad (which is causing very weird scrolling behavior and breaking commenting on issues with existing discussions) with this fix...

```
body .page-sizer {
  top: 40px; // yay no more padding or vh
  left: 0;
  right: 0;
  left: 0;
  bottom: 0;
  overflow: auto;
  padding-left: 0;
  position: absolute;
  width: 100%;
  /* padding-top: 40px; no */
  /* height: 100vh; no don’t do this */
}
```

Here's the deal. You're setting `body .page-sizer` as `100vh` but then putting an additional padding of `40px` which is causing the page to be 40px or so taller than the viewport, making scrolling within issues super-weird and jumpy and also causing the comment form and button to sometimes be inaccessible.

The fix is above. Don't rely on `vh` and padding. Just the wonders of absolute positioning (which you're already using).

**Comment by marydavis** [comment]
@heybenji thanks for the suggestion and was happy to try it, but unfortunately it doesn't work in all situations for us (especially in dealing with our sidebar). I agree the `.page-sizer` needs to go or be reworked, but will need more time and effort to figure out the long term fix :) I will create a card for us to look into this further. Thanks again!
