### ISSUE TITLE
extend done column time

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#314]
**Acceptance Criteria**:
- [ ] switch default to 30 days
- [ ] lean query for cards

Wait for #2974.

**Comment by jwalgran** [comment]
+1

**Comment by steventlamb** [comment]
+1

**Comment by caseypt** [comment]
+1

**Comment by kdeloach** [comment]
+1

**Comment by mmcfarland** [comment]
+1

**Comment by RickMohr** [comment]
+1

**Comment by deeonis** [comment]
+1

**Comment by deeonis** [comment]
Do you have any plans to realize this feature?

**Comment by narqo** [comment]
:+1:

**Comment by jaredj** [comment]
+1

**Comment by teasp00n** [comment]
+1

**Comment by marcoalbarelli** [comment]
+1

**Comment by mhl** [comment]
+1 This would be really helpful for us, as another team that works on two week sprints

**Comment by RichardForshaw** [comment]
+1 GitHub supports this in the 'Pulse' view, so would be nice to see the same thing on Waffle

**Comment by jukibom** [comment]
Yep, would really like to see this feature for our meetings too

**Comment by nickethier** [comment]
:+1:

**Comment by fkh** [comment]
+1

**Comment by alleyhector** [comment]
:+1:

**Comment by alleyhector** [comment]
@fredpe We were thinking of doing something similar but any time you close an issue in Github it will go to the auto-archiving column in Waffle. Am I correct here or is there an additional workaround? Do you not close your issues?

**Comment by klikinsg** [comment]
+1 - cannot wait :)

**Comment by lewfish** [comment]
+1

**Comment by rajadain** [comment]
+1 please!

**Comment by lliss** [comment]
+1

**Comment by jwalgran** [comment]
+1

**Comment by MFDW** [comment]
"add ability to turn off automatic archiving"
+1 

taking control away from people is really sad...

**Comment by katschre** [comment]
+1

**Comment by the-ult** [comment]
Can't wait.
2 weeks default would be great

**Comment by pineholmes** [comment]
Hello @homeyer , can you define option 1? For me I would interpret it as "let the issue lay here for 2 weeks starting from the date when it turned up here". This does not really help people running with two week sprints since the sprints have static start- and end dates. Or, have I misunderstood?

I agree with @exalted : to leave issues as "done" until the sprint is finished, i.e. a given date.

**Comment by shacharz** [comment]
This is a must, the only reason I use waffle is for visibility over issues in GitHub (multiple repositories)
If issues disapear under my watch, it's a major shortcoming

**Comment by shadowbq** [comment]
Smaller projects that are less active and have longer sprints would benefit from a retention time greater than 7 days.

**Comment by josefbrengesjo** [comment]
+1

**Comment by hreintke** [comment]
+1

**Comment by KeithLittle** [comment]
+1

**Comment by winniequinn** [comment]
Please make this happen! This is our team's number one complaint with Waffle. Our sprints are on a two-week cycle so we're always missing issues in the Done column when we do our review. 😥

**Comment by rajadain** [comment]
Hey Everyone,

Since so many people are facing this but it hasn't been addressed so far, here's the workaround that my team uses:

![image](https://cloud.githubusercontent.com/assets/1430060/14970039/de6e69e0-1093-11e6-8155-9bdb9fd0256b.png)

Basically we added a custom "Verified" column where we move cards to that have been merged in, and only move them to "Done" after the sprint finishes. We essentially stopped using "Done" completely, and don't care about those cards at all. Cards in "Verified" are not auto-archived, and allow us to have a reliable count at the end of the two weeks.

Hope this helps some of you.

**Comment by RickMohr** [comment]
Our team uses a similar workaround. In PR text you need to use e.g.
"Connects #134" instead of "Fixes #134" so that merging a PR doesn't close
the issue. Avoiding the "Done" column is also a plus when issues have life
beyond the developer, such as being tested before a release or listed in
release notes. Waffle is flexible enough for such less-developer-centric
workflows, even if the default setup is developer-centric.

On Mon, May 2, 2016 at 6:32 PM, Terence Tuhinanshu <notifications@github.com
> wrote:

> Hey Everyone,
>
> Since so many people are facing this but it hasn't been addressed so far,
> here's the workaround that my team uses:
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/1430060/14970039/de6e69e0-1093-11e6-8155-9bdb9fd0256b.png>
>
> Basically we added a custom "Verified" column where we move cards to that
> have been merged in, and only move them to "Done" after the sprint
> finishes. We essentially stopped using "Done" completely, and don't care
> about those cards at all. Cards in "Verified" are not auto-archived, and
> allow us to have a reliable count at the end of the two weeks.
>
> Hope this helps some of you.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/waffleio/waffle.io/issues/314#issuecomment-216384817>
>



-- 
Rick Mohr, Software Developer
Azavea  |  990 Spring Garden Street, 5th Floor, Philadelphia, PA
T 215.701.7504  |  Web azavea.com <http://www.azavea.com/>  |  @azavea
<http://twitter.com/azavea>

**Comment by codybunea** [comment]
+1 -- having a 2 week default is a large issue for us when reviewing the results of the sprint 2 weeks later.

**Comment by wickdninja** [comment]
+1 not being able to customize this may prevent our team from using this tool :( since we can't track an entire sprint in the "done" column

**Comment by cyrilhamidechi** [comment]
+1

**Comment by virtser** [comment]
+1 its really missing guys!

**Comment by kgiszewski** [comment]
+1, curious why this is a 3 yr old request. Is there a commercial version of this that is supported?

**Comment by roll** [comment]
:+1:

**Comment by ebolloff** [comment]
:+1:

**Comment by oferh** [comment]
+1

**Comment by burtonjc** [comment]
This was just released! You will now see back 30 days in the Done column.
