### ISSUE TITLE
reduce concurrent requests to GitHub API

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#3158]
According to GitHub, they've introduced new rate limits that prevent too many concurrent requests (see slack conversation).

We may be seeing issues for customers related to this already.

Investigate where we're doing these concurrent requests (per access token) and fix the main offenders. 

We may not be able to fix the waffle-iron token, since every board load when you're not logged in uses that. If that's the case, figure out a plan for moving away from our current anonymous board strategy (prompt users to log in for public boards?)

**Comment by homeyer** [comment]
when we load cards, and then sync with github or first create a project and fetch all issues, do we do that in parallel? If so, we probably have to make that sequential. A good reason to move towards columns owning their cards and only fetching a page worth

**Comment by songawee** [comment]
one idea I had to help with the rate limiting is to inspect the headers within the github helper and see about retrying those requests. would be cool if we could solve that app wide in one place. may be a bit harder to accomplish doing it this way though.

**Comment by burtonjc** [comment]
After much deliberation, we decided to ignore this for now because:
1. GitHub has protected themselves against this already
1. We are not seeing any issues on our end (yet)
1. Some of the things we want to pursue in the (somewhat near) future would alleviate much of this

We can revisit this in the event that we start seeing problems arise from being rate limited.
