### ISSUE TITLE
show build statuses on PRs merged to master branch

### ISSUE THREAD

**Issue by marydavis** [waffleio/waffle.io#3321]

**Comment by homeyer** [comment]
status: 
- decided we want to show the merge status in addition to any other commit statuses. This is so that it's visible if someone merged without a previous build passing.
- current code doesn't work with that, since we look for the "context" to replace the last build with the most recent. I think we need to track the merge status separate from the other commit statuses so we can appropriately keep the right ones (still show in the same bar).
