### ISSUE TITLE
Create burndown chart based on labels and/or milestones

### ISSUE THREAD

**Issue by marksupply** [waffleio/waffle.io#3412]
Currently, my team uses labels to organize sprints, and milestones for long-term, well, milestones.

The burndown chart would be incredibly helpful for sprint level tracking and retrospectives. The goal is to help understand our velocity at-a-glance.

connected to #3535

**Comment by grepory** [comment]
This might be considered a separate issue, but I figured I'd throw this in here for an idea as well:

It would be nice to be able to combine milestones or labels in a burndown chart. We use milestones like epics (because we want to see burndown charts with projected delivery dates). They often have shared delivery dates. Being able to see a single burndown (for tracking releases for OKRs) would be really nice.

**Comment by kellihsf** [comment]
We're moving this over to our metrics enhancement card [#1327](https://github.com/waffleio/waffle.io/issues/1327). Please feel free to upvote the issue there. :)
