### ISSUE TITLE
"Go To ..." WaffleMetrics don't act like links.

### ISSUE THREAD

**Issue by schwern** [waffleio/waffle.io#3433]
I small UI nit. I usually want the Board in one tab and the Burndown Chart in another.

On `https://waffle.io/<org>/<repo>/metrics`, I have "Go To Throughput" and "Go To Milestone Burndown". Neither of these act like links in Firefox. I can't cmd-click on them to open in a new tab. Right-click doesn't offer any link options like "open in new tab".

I work around it now by opening Metrics in a new tab and then clicking on "Go To Burndown" but sometimes I forget.

**Comment by kellihsf** [comment]
hi @schwern,

Both of those graphs should work as links in Firefox (and other browsers). Are you on the latest version of Firefox? Feel free to email us at support@waffle.io with more details if you prefer!

**Comment by schwern** [comment]
Hi @kellihsf,

Yes, I just tried it again with Firefox 60.0.1 and Chrome 66.0.3359.181. These are both on Mac. I made sure AdBlock was off.

If I click on them, I get taken to the Throughput or Burndown pages. But if I want to "Open Link In New Tab" I can't. It's not available. I've attached two screenshots to illustrate the difference. And again, this is a very minor problem.

![screen shot 2018-05-23 at 3 24 05 pm](https://user-images.githubusercontent.com/25888/40454379-8068b88c-5e9d-11e8-9ef5-0d74431ae0ea.png)
![screen shot 2018-05-23 at 3 23 52 pm](https://user-images.githubusercontent.com/25888/40454380-808fd78c-5e9d-11e8-8540-b58590dc257f.png)

**Comment by kellihsf** [comment]
hi @schwern, 

Just wanted to follow up here. After confirming with our dev team (and realizing i misread your initial message!), this is a known issue. Currently, you're not able to right click on the graph to open in a new tab, as you've discovered. I'll move this to our "Ideas" column as a feature request for others to find. :)

**Comment by AnaMSteele** [comment]
@schwern we aren't seeing a lot of action via voting on this card just offer that as an update. We have some higher voted known issues we will likely prioritize over this due to demand. If you have an interest, we would love to schedule a short call with you to talk about your use cases in Waffle and better understand the jobs you do in the tool as we continue to build and improve in Waffle. Email ana@waffle,io if you would be game to spend 20 minutes talking about your role on your team and needs from Waffle. Thank you!
