### ISSUE TITLE
update bot.waffle.io

### ISSUE THREAD

**Issue by marydavis** [waffleio/waffle.io#3477]
- [x] add a transparent darker background to header for small screens to make it more readable when over bot image
- [x] add waffle logo and headline that links back to waffle landing page
- [x] add same footer copyrights as landing page
- [x] setup DNS
- [ ] confirm site is working

**Comment by adamzolyak** [comment]
@marydavis how can i view what this site currently looks like?

**Comment by marydavis** [comment]
@adamzolyak click the green bar on the attached PR :)  to see my proposed changes add `/soon.html` to the url

**Comment by adamzolyak** [comment]
@marydavis after reviewing https://deploy-preview-3--eager-lalande-1adfb9.netlify.com/, I think we'd want to keep it very minimal since we'd rather have users move to the marketing site so they can get more info and sign up.  I'd suggest removing most of the content and adding a CTA button to go to waffle.io/features/automation.  That way we have the microsite ready for when we have more info to add about SwagBot.

Mockup
![Fullscreen_8_1_18__8_36_AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5457b48ff284760200e70666/125516c66e82c728ace21e0d46ce81962f9180bb8aecb17cfc62a1ab781e184c713bf07d4fa4ce6af3006b1300051bff054a5556f9fbdc2ba2b76f26df5c0fe883650e27c53847f9bc841dbf13a632c91edbe2e3d7158abd7f37ed998e48341f001b8afe5e31a3984bcb5ef659ac.png)

**Comment by marydavis** [comment]
@adamzolyak i think you may have missed my previous comment. the url for the one i was updating was https://deploy-preview-3--eager-lalande-1adfb9.netlify.com/soon.html. also, if you look at the task list - the only things i was going to add was the same footer as the marketing site and small section that links to the marketing site.

**Comment by marydavis** [comment]
@adamzolyak also all that content was from the original site, i didn't edit that page at all.

**Comment by marydavis** [comment]
@adamzolyak i can finish this, i just wanted to know if this is the way we want to go before putting in too much effort

**Comment by adamzolyak** [comment]
@marydavis yep, your suggestions make sense.  Do it!
