### ISSUE TITLE
card doesn't display all labels

### ISSUE THREAD

**Issue by MiniDigger** [waffleio/waffle.io#3516]
compare the card:
https://waffle.io/VoxelGamesLib/VoxelGamesLibv2/cards/5b07b63d36bc2200a73112ba
to the actual github issue:
https://github.com/VoxelGamesLib/VoxelGamesLibv2/issues/153
its missing labels.
when I click to edit labels on the card, all labels are selected.  
this also affects which column the card is placed in so I doubt that its a browser issue.  
the issue was created on github with all 5 labels, but waffle only picked up 2.

**Comment by kellihsf** [comment]
Hi @MiniDigger, 

Waffle doesn't display any column labels on card (ex: in progress, needs review) which is why you're not seeing those few labels on your Waffle card. 

It looks like on that particular card, there are 3 column labels that were added in GitHub: "Priority: High" for the High column, "Status: Accepted" for the To Do column, and "Type: New Gamemode" for the Gamemodes column. 

You may run into some trouble in Waffle by having 3 different column labels on 1 card since a card can only exist in 1 column at a time. Waffle goes off of those column labels to determine which column a card belongs to. :)

**Comment by MiniDigger** [comment]
Ahhh ok, good to know. Guess I need to rethink my layout a bit then. Thanks!
