### ISSUE TITLE
GitHub issues transferred to another repo are not deleted from the board

### ISSUE THREAD

**Issue by pvdlg** [waffleio/waffle.io#3710]
GitHub just released a new feature in beta to transfer issues from one repo to another in the same organization: https://help.github.com/articles/transferring-an-issue-to-another-repository/

After an issue is transferred it still appears in the board and it can't be moved or edited. The issue should be removed from the board.

Here a few example from the https://waffle.io/semantic-release/semantic-release board:
- semantic-release/semantic-release#911
- semantic-release/semantic-release#861
- semantic-release/semantic-release#365
- semantic-release/semantic-release#372
- semantic-release/semantic-release#377
- semantic-release/semantic-release#333 
- semantic-release/semantic-release#434
- semantic-release/semantic-release#804

**Comment by AnaMSteele** [comment]
Unfortunately that will keep happening, since we have not begun supporting that beta feature. We do not have this on our near term roadmap for transparency. We are aware and will be closing this issue until our team has prioritized it. Thank you. 

Please contact support@waffle.io with the list of issues you would like us to manually delete from your board for you in the meantime.

**Comment by homeyer** [comment]
I'll dig into this to see if we can prevent the old cards from remaining. ~ Andrew

**Comment by homeyer** [comment]
GitHub's API currently gives us no notification of a transfer happening, the issue literally disappears 😦. No webhook either. This breaks our sync process, since we rely on fetching updates based on the "last updated at" date.

We've opened a ticket with GitHub support.

**Comment by BAMason** [comment]
Unfortunately, the current webhook that comes in for a `transferred` event represents an issue that has been deleted in GitHub.  This means we can't use the repo, number or node_id to determine where the new issue has landed.

The best we can do in this instance is remove the card related to the old issue so it doesn't get stuck on the board. There is also an `opened` event that comes through for the receiving repo so a new card should appear on the board as soon as that webhook is processed or the board is refreshed.

**Please note**: when transferring issues, this is a delete & create action in GitHub so you will lose any sizing and ranking details associated with that Waffle card.

**Comment by BAMason** [comment]
@tnrich We did the best we could with a beta feature ;)  I solved for this using the webhook events that were available at the time. If you do not have webhooks enabled for Waffle or there was an event that was not triggered, then cards would not be removed.

Since the time this has been closed, GitHub has updated their API responses to provide additional context for deleted and transferred issues which means we can now handle these scenarios more gracefully without relying on webhooks.  You can follow that work [here](https://github.com/waffleio/waffle.io/issues/3741).

We can manually clean up errant cards remaining on your board if you'd like to open up a support case with us and include the repo & issue number details.  Please also keep in mind that this functionality is still in beta, things are still changing rapidly and we respond as quickly as we are able with the capabilities that are proffered.

**Comment by tnrich** [comment]
@BAMason thanks for the response. I've deleted all affected issues manually and will wait until #3741 is ready to use the move issues in github.

**Comment by NathanSweet** [comment]
I have 2 issues on my Waffle: the transferred issue and the old issue. The old issue cannot be modified or closed. If Waffle detects that an issue does not exist, it would be nice if it would clean it up rather than leave a card I cannot get rid of. Is it possible to delete the old issue? Do I need to delete the transferred issue and recreate the issue manually?

**Comment by davidschober** [comment]
Hello, 

I'm having the same problem and I can't seem to take any action on the affected issues (delete, close, move within a column). Unfortunately we got a bit trigger happy and moved a bunch of issues before realizing this.

**Comment by BAMason** [comment]
We've just released the ability to delete a card from your Waffle board so you can resolve these "stuck" card issues without contacting Waffle support.

Please note that at this time GitHub does not support deleting issues via API.  This means if you delete a card that _has_ a related issue in GitHub, that issue will persist even though the card no longer exists on your board.

Any updates to that issue will cause our sync process to pick up the change and re-add the card.  **The delete card option should only be used for stuck cards that have already been deleted or transferred within GitHub.** (don't worry, we added a confirmation message to remind you 😄)

**Comment by NathanSweet** [comment]
@BAMason Thanks for the fast solution!

**Comment by tnrich** [comment]
@BAMason yep thanks again! @siobahndavis it should be safe to use the transfer issues within github now!

**Comment by dansomething** [comment]
I just ran into the transfer issue today, but "Delete Card" from Waffle is failing. The `DELETE` API request to https://api.waffle.io/cards/5c5c6487431087008a1ffdc0 is failing with a 404.

Here's the full request log.
[waffle-delete-card.har.zip](https://github.com/waffleio/waffle.io/files/2842000/waffle-delete-card.har.zip)

Any suggestions on how to work around this would be much appreciated.

**Comment by marydavis** [comment]
Hey @dansomething - it looks like something might be wrong with that card specifically, would you mine emailing us at `help@waffle.io`?
