### ISSUE TITLE
GitHub label not visible in default view

### ISSUE THREAD

**Issue by jjawad-google** [waffleio/waffle.io#3763]
We have a GitHub label called "triaged: yes" which we would like to be a visible label in waffle. Even though the "triaged: yes" label is associated with the issue in the attached screen shot, it is not visible in waffle and requires a search of the label in waffle before we are able to determine if the issue was assigned the label or not. 
![triagedyes](https://user-images.githubusercontent.com/38964959/50460785-e31cbb00-092d-11e9-97b3-c1abb5ae4f20.png)

**Comment by burtonjc** [comment]
This is most likely because "triaged: yes" is also a column label. Waffle boards hide the labels that are associated with columns since that data is visualized by the column itself. We have a [help article](https://help.waffle.io/waffle-boards/creating-project-boards/how-do-i-customize-my-waffle-board-columns) that explains it more in depth. If you really want to see that label, you would just need to create a different label for the column to use.

I'm going to go ahead and close this, but feel free to reopen it if you have other questions on this!

**Comment by jjawad-google** [comment]
Hi @burtonjc thank you for looking into this issue for us. I've attached a screen shot of our column labels. We don't have a column called "triaged: yes," however we do have one called "Triaged."  I tried renaming the column named "Triaged" to a column named "Reviewed," logged out / logged back into waffle.io and still don't see the triaged: yes label in each card. 

![wafflecolumnlables](https://user-images.githubusercontent.com/38964959/50617348-95f69700-0ea1-11e9-8e24-a96c1f189d71.png)

**Comment by burtonjc** [comment]
The column name is different from the column label. On the column settings page, you should also be able to change the label associated with each column. Does the column named "Triaged" use the "triaged: yes" label?

Like this on the column settings page:
![tempsnip](https://user-images.githubusercontent.com/443084/50649264-a0b13a80-0f3a-11e9-8009-55f4c8474abb.png)

**Comment by jjawad-google** [comment]
The column named "Triaged" does use the "triaged: yes" label as shown below. 

![columnname-label](https://user-images.githubusercontent.com/38964959/50662938-d7984800-0f5c-11e9-99ad-b3f3df1f6fb7.png)
