### ISSUE TITLE
Add "print" view/option to print out issue cards

### ISSUE THREAD

**Issue by jcorbett** [waffleio/waffle.io#844]

**Comment by notionparallax** [comment]
We've been using [git2pdf](http://www.pocketworks.co.uk/blog/2014-07-01-announcing-git2pdf) and so far it's great.
It would be even better if we could print from Waffle because it would put the issues in order.

I like that git2pdf puts an issue on each page of the pdf. This means that in acrobat you can chose how many issues to tile onto each page.

**Comment by notionparallax** [comment]
In the meantime, we made this dirty hack: https://github.com/notionparallax/Waffle-printer

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
